### ISSUE TITLE
Can't continue past recent v2.1.0 release notes

### ISSUE THREAD

**Issue by rubin110** [chrisxclash/play-midnight#13]
There is currently no way for me to continue past the release notes. It looks like the content of the notes continues down past the end of the view port, but I don't see any way to scroll. There is no scroll bar, pressing down, space, page down, or using the mouse to scroll doesn't work. Nor does hitting escape on my keyboard. Please see attached screen shot.

I'll try plugging into a larger monitor in a bit to see if there's more of the screen I can interact with.

![20150525113200-selection](https://cloud.githubusercontent.com/assets/222551/7800928/b3903030-02d1-11e5-9d50-25f0d505193b.png)

**Comment by rubin110** [comment]
Here's it on my larger monitor...

![20150525115914-selection](https://cloud.githubusercontent.com/assets/222551/7801190/93f40cc0-02d5-11e5-8286-5b2d949972a9.png)

**Comment by chrisxclash** [comment]
@rubin110 Yeah that was an issue I was trying to tackle this morning. I didn't notice it til it was brought up by someone on reddit. I actually pushed version 2.1.1 to hopefully fix it, but I'm not 100% if it did indeed fix it or not.

Can you go to chrome://extensions, check the "Developer mode" checkbox, then click update plugins and ensure you're on 2.1.1 and then try it again?

Thanks!

**Comment by chrisxclash** [comment]
Also, what version of Chrome are you on? I'm using flexbox and apparently it's still in it's finicky stages. I figured it would be fine to use since Google uses it throughout Play Music in the new update, but apparently I was wrong, or something changed in the flexbox spec.

**Comment by rubin110** [comment]
I'm using Chrome unstable/dev 44.0.2403.9.

The issue is fixed with 2.1.1, however when reloading Play Music after re-enabling the plugin no release notes were displayed.

**Comment by chrisxclash** [comment]
Ah okay, it seems something changed in the dev version of Chrome then. The other guy had the same issue with that happening in version 44. I'm only on the stable 43, so that's why I couldn't see that issue.

There was some random issue with it squishing the header/footer which I did fix in 2.1.1, but I could never reproduce the non-overflow filling the page bug.

The modal is designed to not show up again once you click the button to prevent annoying people, so if you clicked the button before that's probably why you didn't see it. I'll have to snag the dev build of Chrome and play with it in there I suppose.

**Comment by chrisxclash** [comment]
Nevermind, I figured it out. I'm an idiot. My modal templates had an extra nested div that was breaking how the flexbox determined height or something along those lines. Going to push out 2.1.2 in the next hour or so and get that fixed.
