### ISSUE TITLE
Color matching on GPM logo

### ISSUE THREAD

**Issue by SpiderJeru** [chrisxclash/play-midnight#28]
Hello,

Currently the GPM logo in the top left corner is orange (default theme).
It would be nice if it matched the custom accent color, but it seems it is not html but a set image. Therefore I think it could be **set to a light grey** to fit with any custom accent color?

Thanks again for the brilliant extension!
Cheers

**Comment by geudrik** [comment]
That image is the favicon, so setting it either requires b64 injection of an image, or a hard-coded URL. `href="data:image/png;base64,xxxx` in the favicon would allow for generated favicons to be injected, but IIRC chrome caches that.

**Comment by chrisxclash** [comment]
I think he's actually talking about the Play Music logo in the sidebar. The way I have my js set up right now it's kind of annoying to get it working since Google uses something React-like that automatically re-renders the image if you change it. I've had this on my list for my next version of PM when I get around to it though.

**Comment by chrisxclash** [comment]
Just fixed this one up in 37b9d65 after looking into it with some css changes instead of js
